version: "2"

services:
  webui-aria2:
    container_name: webui-aria2
    image: registry.cn-hangzhou.aliyuncs.com/jren/aria2-webui
    ports:
      - 9100:8080
      - 6800:6800
      - 6999:6999
      - 6998:6998
    volumes:
      - /f/Data/Download:/data
      - ./aria2.conf:/home/dummy/.aria2/aria2.conf
      - ./dht.dat:/home/dummy/.aria2/dht.dat
    restart: always